### ISSUE TITLE
Concerning @weakify(super): Is this okay?

### ISSUE THREAD

**Issue by nikkonikko** [jspahrsummers/libextobjc#106] opened 2016-01-18 11:38 UTC
I just want to be sure, will this work for 'super' since = self or?

@weakify(self);
[super METHOD: ^{  @strongify(self);
   [self METH1];
   [super METH2];
}];

**Comment by jspahrsummers** [comment] 2016-01-18 18:19
This will probably not work as intended. I've never tried.

**Comment by nikkonikko** [comment] 2016-02-02 08:27
You have any idea for a work-around then?
Or should I just define a "weakSuper" instead of the 'super'?
Thanks.

**Comment by jspahrsummers** [comment] 2016-02-02 08:35
I guess I would factor out this logic into another method on `self`, so it's clear to you and future readers of the code. Even if you figured out how to make a `weakSuper`, it may not be obvious how it works, or that it works as intended.

**Comment by nikkonikko** [comment] 2016-02-25 12:40
It will be nice if you could notify me in this thread, when you do the fix :) Thanks and thanks for this library.

**Comment by jspahrsummers** [comment] 2016-02-25 16:00
I will not be making any fix for this. It's nothing to do with the library, and everything to do with Objective-C.

You should _factor out your `super` call into a method on `self`_, and invoke that from the block instead.

**Closed by jspahrsummers** 2016-02-25 16:00 UTC
